### ISSUE TITLE
Use single struct with union rather than struct inheritance?

### ISSUE THREAD

**Issue by RobertCochran** [JoshuaBrockschmidt/bigram_quoter#3]
As such :

``` C++
enum item_type {
        MARKER, WORD
};

union item_value {
        Markers marker;
        std::string word;
};

struct item {
        enum item_type type;
        union item_value value;
};
```

Used as such:

``` C++
/* When writing */
my_item.type = WORD; my_item.value.word = std::string("over9k");

/* When reading */
if (my_item.type == WORD)
        processTheWord(my_item.value.word);
```

This (imo) is more readable, is clearer, and would allow for removing
the typecasts that litter the code when you need to cast between the
current ParserItem_marker and ParserItem_word structures.

EDIT: Add syntax highlighting. Pretty colors are a must.

**Comment by jcbrockschmidt** [comment]
In defense of your proposal:
- Syntactically, this looks simpler. If we were to employ this, I would only recommend that we change the 'enum' to an 'enum struct' to avoid cluttering the main namespace.
- Your method may be a bit fast due to a lack of inheritance and such. I'm not familiar enough with how C++ compiles to know if this benefit would be negliable or not though.

On the flip side, I have a few counter-arguments to consider:
- With your approach, there would indefinetly be some unused memory. For each word, there would be an unused marker value. For each marker, there would be an unused word value. With the small scale of this project, this won't make-or-break anything. It just feels a bit messy. But correct me if this is in fact common practice.
- C-style typecast have virtually no overhead (if any; I'm not 100% sure). Removing them will only provide syntax benefits.
- The current method for managing parser items seems perfectly acceptable in a C++ environment. And it's already pretty concise.

I personally think the tie-breaker is going to whether or not the performance gained by the lack of inheritance overshadows the hit taken by the unused memory.

**Comment by RobertCochran** [comment]
Good points.

It **may** end up being faster. That said, it was not a consideration for this
proposal, though. I wholly suggested this for the syntactic improvements.

This particular method of using one structure to store multiple data types in
the particular way I present it is a common one.

There would, admittedly, be a little bit of unused memory, but a union only
takes up the space of the biggest member (which I believe would be std::string),
but this does not account for any dynamically allocated memory allocated by the
string (I truly have no idea of how a std::string works internally, but I'm
guessing that it does dynamic allocation). The union itself is the size of its
biggest member.

On the flip side of using slightly more memory, you end up removing a couple
of local variables whose only purpose is to hold the result of the cast.
(Since we're splitting hairs about our memory usage here :P)

In all honesty, the total memory difference is likely to be something like
+/- 8 bytes per ParserItem. Probably less even. Honestly, negligible in most
situations. Certainly a difference small enough that I wouldn't want it to be the
reason to decline a change whose purpose is for clarity.

In my opinion, the constant typecasting has an obscuring effect - the only time
I see in the code that a ParserItem is used directly is to check the type
member, then is typecasted directly afterwards. This kinda screams at me that
the data structures need to be redesigned, but again, this is a personal opinion.

EDIT: Also, the changes in the namespacing are totally fine. Example was
deliberately simplified.

**Comment by RobertCochran** [comment]
Screw that idea. The compiler does **not** like having 'nontrivial' classes
within an enum, because that apparently 'confuses the compiler' (which is utter
crap, by the way). The options are:
- Abandon idea entirely. Easiest, but still leaves code messy
- Use a character pointer rather than a std::string
  (at which point, imo, I'd just go ahead and rewrite in C, personally)
- Come up with a different method to clean up code

I know which one is _my_ choice, but it's not up to me.

(Forgive me for being snarky and all that. I'm frustrated at the language, not you.)

**Comment by jcbrockschmidt** [comment]
My apologies. I misunderstood how unions work. I was thinking of them as structs _facepalm_. If we can get your proposal working, I'm all for it now.

**Comment by RobertCochran** [comment]
It's been months, and it would take a rewrite of the parser to do this, which
neither of us feel like doing any time soon. Closing.
